# Generated by Django 4.0.6 on 2022-07-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('Query', models.TextField()),
                ('City', models.CharField(max_length=150)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
